layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 200
  exclude:
    archived: true
    forks: true
    projects:
      - tda-webhooks-tradingview
      - personal-website
      - vercel
      - hyperdrive
      - asmaa.dev-2
      - nodetest
      - amazon-clone
      - asmaa.dev
      - ts-mui-nextjs-starter
      - blkpvnthr
      - CMSC203
      - CMSC203_Lab3


social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: https://www.linkedin.com/in/blkpvnthr/
  # mastodon: your_username
  # medium: your_username
  stackoverflow: blkpvnthr
  # telegram: your_username
  twitter: blkpvnthr
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Quantitative Finance
    web_url: https://github.com/topics/quantitative-finance
    image_url: https://user-images.githubusercontent.com/7336481/133036451-e1f2f12b-9e96-4a0f-8c69-4f630bb8ded3.gif

  - name: Web Design
    web_url: https://github.com/topics/php
    image_url: https://i.pinimg.com/originals/cf/d1/28/cfd128e9bdc5e0f3ffe23564f56e3aad.gif
  
  - name: Quantum Computing
    web_url: https://github.com/topics/quantum-machine-learning
    image_url: https://scitechdaily.com/images/Animated-Illustration-Atom.gif
  
  - name: Machine Learning
    web_url: https://github.com/topics/machine-learning
    image_url:  https://media.licdn.com/dms/image/v2/C4D12AQHeek1XA-HYwQ/article-cover_image-shrink_720_1280/article-cover_image-shrink_720_1280/0/1616559535106?e=2147483647&v=beta&t=G4sPqcdEAvo6ToKpP1b68zh_1S94-rHjl5jN8i9JYHQ

  - name: Data Science
    web_url: https://github.com/topics/data-science
    image_url: https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/1cc5e3ff-37e5-4b9c-abf4-92304fafa4c9/deekqx1-20d6363f-185e-4f8d-a748-f5b3f3b8fdde.gif?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzFjYzVlM2ZmLTM3ZTUtNGI5Yy1hYmY0LTkyMzA0ZmFmYTRjOVwvZGVla3F4MS0yMGQ2MzYzZi0xODVlLTRmOGQtYTc0OC1mNWIzZjNiOGZkZGUuZ2lmIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.bQwR0OGahVNiMtiHhvn95SFiuAZKxapsWSr_AbMK_Oc
    
  - name: iOS Development
    web_url: https://github.com/topics/ios
    image_url: https://i.pinimg.com/originals/d7/41/5b/d7415bfddb6f42a8272b80b2c8be311d.gif
